version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SS29lose
      - POSTGRES_DB=usersdb

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
