services:
  match-service:
    build: .
    container_name: match-service
    ports:
      - "8083:8083"
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=admin
    depends_on:
      - neo4j
